import { PERMISSIONS } from './permissions.js'

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_STAFF_ACTIVITY,
    PERMISSIONS.VIEW_WORKING_HOURS,
    PERMISSIONS.MANAGE_CHATS,
    PERMISSIONS.RESPOND_CHATS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],

  staff: [
    PERMISSIONS.RESPOND_CHATS,
    PERMISSIONS.VIEW_WORKING_HOURS,
  ],

  intern: [
    PERMISSIONS.RESPOND_CHATS,
  ],

  client: [
    PERMISSIONS.SUBMIT_FORMS,
    PERMISSIONS.VIEW_PROGRESS,
  ],
}
